# get data from database

In [1]:
from cmschina_tianyan.session import CmsSession
import pandas as pd
dataset = CmsSession.init(appId="cb632213cf764a019b32f8cc9d2040b7", appSecret="b23700b9fbf0090709c7b72ac0fdcb390cd19cc663bcf1c7a07c12b8c32bf377")

[2022-09-29T14:53:14.090272+0800] [29609] [INFO] [session.py] [63] PROD Env Init Completed!

In [2]:
stock_code = '603355' #上交所
trade_date_list = [
'20220901','20220902',
'20220905','20220906','20220907','20220908','20220909',
'20220913','20220914','20220915','20220916',
'20220919','20220920','20220921','20220922','20220923',
'20220801','20220802','20220803','20220804','20220805',
'20220808','20220809','20220810','20220811','20220812',
'20220815','20220816','20220817','20220818','20220819',
'20220822','20220823','20220824','20220825','20220826',
'20220829','20220830','20220831',
'20220701',
'20220704','20220705','20220706','20220707','20220708',
'20220711','20220712','20220713','20220714','20220715',
'20220718','20220719','20220720','20220721','20220722',
'20220725','20220726','20220727','20220728','20220729',
'20220601','20220602',
'20220606','20220607','20220608','20220609','20220610',
'20220613','20220614','20220615','20220616','20220617',
'20220620','20220621','20220622','20220623','20220624',
'20220627','20220628','20220629','20220630'
]
#上交所取数

for trade_date in trade_date_list:
    sql = f''' 
    SELECT * 
    FROM quota_01.sh_stock_snapshot
    where security_id = '{stock_code}' and date_time > {trade_date}000000 and date_time < {int(trade_date)+1}000000
    '''

    df_sh = dataset.get_data(sql)
    save_path = f'./stock_data/sh_exchange/{stock_code}/{stock_code}_{trade_date}.pkl'
    df_sh.to_pickle(save_path)

[2022-09-29T14:53:27.289963+0800] [29609] [DEBUG] [tianyan_provider.py] [130] retrieve total 4648 rows of data
[2022-09-29T14:53:43.817876+0800] [29609] [DEBUG] [tianyan_provider.py] [130] retrieve total 4496 rows of data
[2022-09-29T14:54:00.098016+0800] [29609] [DEBUG] [tianyan_provider.py] [130] retrieve total 4129 rows of data
[2022-09-29T14:54:16.707706+0800] [29609] [DEBUG] [tianyan_provider.py] [130] retrieve total 4321 rows of data
[2022-09-29T14:54:32.895685+0800] [29609] [DEBUG] [tianyan_provider.py] [130] retrieve total 3760 rows of data
[2022-09-29T14:54:44.515792+0800] [29609] [DEBUG] [tianyan_provider.py] [130] retrieve total 4441 rows of data
[2022-09-29T14:54:56.429657+0800] [29609] [DEBUG] [tianyan_provider.py] [130] retrieve total 4288 rows of data
[2022-09-29T14:55:13.246206+0800] [29609] [DEBUG] [tianyan_provider.py] [130] retrieve total 4422 rows of data
[2022-09-29T14:55:29.679683+0800] [29609] [DEBUG] [tianyan_provider.py] [130] retrieve total 4200 rows of data
[2022-09-29T14:55:46.339648+0800] [29609] [DEBUG] [tianyan_provider.py] [130] retrieve total 4208 rows of data
[2022-09-29T14:56:03.012221+0800] [29609] [DEBUG] [tianyan_provider.py] [130] retrieve total 4399 rows of data
[2022-09-29T14:56:14.798865+0800] [29609] [DEBUG] [tianyan_provider.py] [130] retrieve total 4167 rows of data
[2022-09-29T14:56:26.179764+0800] [29609] [DEBUG] [tianyan_provider.py] [130] retrieve total 4097 rows of data
[2022-09-29T14:56:37.856056+0800] [29609] [DEBUG] [tianyan_provider.py] [130] retrieve total 4113 rows of data
[2022-09-29T14:56:49.214056+0800] [29609] [DEBUG] [tianyan_provider.py] [130] retrieve total 4070 rows of data
[2022-09-29T14:57:01.147774+0800] [29609] [DEBUG] [tianyan_provider.py] [130] retrieve total 3835 rows of data
[2022-09-29T14:57:13.198687+0800] [29609] [DEBUG] [tianyan_provider.py] [130] retrieve total 4793 rows of data
[2022-09-29T14:57:29.243139+0800] [29609] [DEBUG] [tianyan_provider.py] [130] retrieve total 4727 rows of data
[2022-09-29T14:57:45.831022+0800] [29609] [DEBUG] [tianyan_provider.py] [130] retrieve total 4503 rows of data
[2022-09-29T14:58:01.598734+0800] [29609] [DEBUG] [tianyan_provider.py] [130] retrieve total 4435 rows of data
[2022-09-29T14:58:17.684072+0800] [29609] [DEBUG] [tianyan_provider.py] [130] retrieve total 4125 rows of data
[2022-09-29T14:58:32.713958+0800] [29609] [DEBUG] [tianyan_provider.py] [130] retrieve total 3921 rows of data
[2022-09-29T14:58:49.005027+0800] [29609] [DEBUG] [tianyan_provider.py] [130] retrieve total 4366 rows of data
[2022-09-29T14:59:04.482093+0800] [29609] [DEBUG] [tianyan_provider.py] [130] retrieve total 4044 rows of data
[2022-09-29T14:59:21.206948+0800] [29609] [DEBUG] [tianyan_provider.py] [130] retrieve total 4221 rows of data
[2022-09-29T14:59:36.908041+0800] [29609] [DEBUG] [tianyan_provider.py] [130] retrieve total 4059 rows of data
[2022-09-29T14:59:48.698414+0800] [29609] [DEBUG] [tianyan_provider.py] [130] retrieve total 4420 rows of data
[2022-09-29T15:00:04.867238+0800] [29609] [DEBUG] [tianyan_provider.py] [130] retrieve total 4317 rows of data
[2022-09-29T15:00:20.315708+0800] [29609] [DEBUG] [tianyan_provider.py] [130] retrieve total 3611 rows of data
[2022-09-29T15:00:41.038805+0800] [29609] [DEBUG] [tianyan_provider.py] [130] retrieve total 3867 rows of data
[2022-09-29T15:01:03.141353+0800] [29609] [DEBUG] [tianyan_provider.py] [130] retrieve total 4078 rows of data
[2022-09-29T15:01:19.250470+0800] [29609] [DEBUG] [tianyan_provider.py] [130] retrieve total 4371 rows of data
[2022-09-29T15:01:36.028975+0800] [29609] [DEBUG] [tianyan_provider.py] [130] retrieve total 4280 rows of data
[2022-09-29T15:01:57.524516+0800] [29609] [DEBUG] [tianyan_provider.py] [130] retrieve total 4222 rows of data
[2022-09-29T15:02:14.036619+0800] [29609] [DEBUG] [tianyan_provider.py] [130] retrieve total 3058 rows of data
[2022-09-29T15:02:34.808887+0800] [29609] [DEBUG] [tianyan_provider.py] [130] retrieve total 4776 rows of data
[2022-09-29T15:02:55.201896+0800] [29609] [DEBUG] [tianyan_provider.py] [130] retrieve total 4624 rows of data
[2022-09-29T15:03:11.551282+0800] [29609] [DEBUG] [tianyan_provider.py] [130] retrieve total 4546 rows of data
[2022-09-29T15:03:32.290888+0800] [29609] [DEBUG] [tianyan_provider.py] [130] retrieve total 4540 rows of data
[2022-09-29T15:03:52.025156+0800] [29609] [DEBUG] [tianyan_provider.py] [130] retrieve total 3494 rows of data
[2022-09-29T15:04:08.593642+0800] [29609] [DEBUG] [tianyan_provider.py] [130] retrieve total 3849 rows of data
[2022-09-29T15:04:27.841684+0800] [29609] [DEBUG] [tianyan_provider.py] [130] retrieve total 3787 rows of data
[2022-09-29T15:04:42.969817+0800] [29609] [DEBUG] [tianyan_provider.py] [130] retrieve total 3713 rows of data
[2022-09-29T15:05:02.803025+0800] [29609] [DEBUG] [tianyan_provider.py] [130] retrieve total 4550 rows of data
[2022-09-29T15:05:22.955760+0800] [29609] [DEBUG] [tianyan_provider.py] [130] retrieve total 4629 rows of data
[2022-09-29T15:05:43.472820+0800] [29609] [DEBUG] [tianyan_provider.py] [130] retrieve total 4851 rows of data
[2022-09-29T15:06:03.544898+0800] [29609] [DEBUG] [tianyan_provider.py] [130] retrieve total 4688 rows of data
[2022-09-29T15:06:23.819739+0800] [29609] [DEBUG] [tianyan_provider.py] [130] retrieve total 4656 rows of data
[2022-09-29T15:06:39.226330+0800] [29609] [DEBUG] [tianyan_provider.py] [130] retrieve total 4441 rows of data
[2022-09-29T15:06:59.659984+0800] [29609] [DEBUG] [tianyan_provider.py] [130] retrieve total 4697 rows of data
[2022-09-29T15:07:15.944963+0800] [29609] [DEBUG] [tianyan_provider.py] [130] retrieve total 4657 rows of data
[2022-09-29T15:07:35.191026+0800] [29609] [DEBUG] [tianyan_provider.py] [130] retrieve total 4161 rows of data
[2022-09-29T15:07:55.123055+0800] [29609] [DEBUG] [tianyan_provider.py] [130] retrieve total 4072 rows of data
[2022-09-29T15:08:10.897952+0800] [29609] [DEBUG] [tianyan_provider.py] [130] retrieve total 4209 rows of data
[2022-09-29T15:08:30.484829+0800] [29609] [DEBUG] [tianyan_provider.py] [130] retrieve total 4079 rows of data
[2022-09-29T15:08:46.287442+0800] [29609] [DEBUG] [tianyan_provider.py] [130] retrieve total 4200 rows of data
[2022-09-29T15:09:01.395620+0800] [29609] [DEBUG] [tianyan_provider.py] [130] retrieve total 3987 rows of data
[2022-09-29T15:09:16.971573+0800] [29609] [DEBUG] [tianyan_provider.py] [130] retrieve total 3767 rows of data
[2022-09-29T15:09:37.807620+0800] [29609] [DEBUG] [tianyan_provider.py] [130] retrieve total 4804 rows of data
[2022-09-29T15:09:58.545878+0800] [29609] [DEBUG] [tianyan_provider.py] [130] retrieve total 4742 rows of data
[2022-09-29T15:10:17.183919+0800] [29609] [DEBUG] [tianyan_provider.py] [130] retrieve total 4589 rows of data
[2022-09-29T15:10:36.257101+0800] [29609] [DEBUG] [tianyan_provider.py] [130] retrieve total 4141 rows of data
[2022-09-29T15:10:55.982942+0800] [29609] [DEBUG] [tianyan_provider.py] [130] retrieve total 4049 rows of data
[2022-09-29T15:11:11.140378+0800] [29609] [DEBUG] [tianyan_provider.py] [130] retrieve total 4106 rows of data
[2022-09-29T15:11:30.530463+0800] [29609] [DEBUG] [tianyan_provider.py] [130] retrieve total 4324 rows of data
[2022-09-29T15:11:45.752689+0800] [29609] [DEBUG] [tianyan_provider.py] [130] retrieve total 4200 rows of data
[2022-09-29T15:12:01.213224+0800] [29609] [DEBUG] [tianyan_provider.py] [130] retrieve total 3851 rows of data
[2022-09-29T15:12:22.200889+0800] [29609] [DEBUG] [tianyan_provider.py] [130] retrieve total 4058 rows of data
[2022-09-29T15:12:40.632394+0800] [29609] [DEBUG] [tianyan_provider.py] [130] retrieve total 3721 rows of data
[2022-09-29T15:13:00.523520+0800] [29609] [DEBUG] [tianyan_provider.py] [130] retrieve total 4295 rows of data
[2022-09-29T15:13:20.057869+0800] [29609] [DEBUG] [tianyan_provider.py] [130] retrieve total 4105 rows of data
[2022-09-29T15:13:35.266189+0800] [29609] [DEBUG] [tianyan_provider.py] [130] retrieve total 4240 rows of data
[2022-09-29T15:13:53.954675+0800] [29609] [DEBUG] [tianyan_provider.py] [130] retrieve total 4094 rows of data
[2022-09-29T15:14:14.247128+0800] [29609] [DEBUG] [tianyan_provider.py] [130] retrieve total 3974 rows of data
[2022-09-29T15:14:33.960876+0800] [29609] [DEBUG] [tianyan_provider.py] [130] retrieve total 4179 rows of data
[2022-09-29T15:14:54.595638+0800] [29609] [DEBUG] [tianyan_provider.py] [130] retrieve total 3910 rows of data
[2022-09-29T15:15:14.783117+0800] [29609] [DEBUG] [tianyan_provider.py] [130] retrieve total 4124 rows of data
[2022-09-29T15:15:36.186155+0800] [29609] [DEBUG] [tianyan_provider.py] [130] retrieve total 3872 rows of data
[2022-09-29T15:15:52.105090+0800] [29609] [DEBUG] [tianyan_provider.py] [130] retrieve total 3726 rows of data
[2022-09-29T15:16:13.461143+0800] [29609] [DEBUG] [tianyan_provider.py] [130] retrieve total 3898 rows of data
[2022-09-29T15:16:34.511176+0800] [29609] [DEBUG] [tianyan_provider.py] [130] retrieve total 4216 rows of data

# get data from local

In [3]:
import pandas as pd
stock_code = '603355'
trade_date = '20220919'
read_path = f'./stock_data/sh_exchange/{stock_code}/{stock_code}_{trade_date}.pkl'

df_sh_local = pd.read_pickle(read_path)

df_sh_local

,auto_id,task_id,file_id,security_id,date_time,pre_close_px,open_px,high_px,low_px,last_px,...,etf_sell_number,etf_sell_amount,etf_sell_money,avg_px,close_px,msg_seq_num,sending_time,war_lower_px,trading_phase_code,num_image_status
0,48737182150,1010490,1007576,603355,20220919091507,30.54,0.00,0.0,0.0,0.00,...,0,0,0.0,0.000,0.00,10916,20220919091506,0.0,C111,1
1,48737923950,1010490,1007576,603355,20220919091510,30.54,0.00,0.0,0.0,0.00,...,0,0,0.0,0.000,0.00,11009,20220919091509,0.0,C111,1
2,48737262063,1010490,1007576,603355,20220919091622,30.54,0.00,0.0,0.0,0.00,...,0,0,0.0,0.000,0.00,12516,20220919091621,0.0,C111,1
3,48737350440,1010490,1007576,603355,20220919091752,30.54,0.00,0.0,0.0,0.00,...,0,0,0.0,0.000,0.00,14964,20220919091751,0.0,C111,1
4,48737368389,1010490,1007576,603355,20220919091813,30.54,0.00,0.0,0.0,0.00,...,0,0,0.0,0.000,0.00,15674,20220919091812,0.0,C111,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4162,48747812143,1010490,1007576,603355,20220919150001,30.54,31.32,32.1,30.6,31.56,...,0,0,0.0,31.519,0.00,3964015,20220919150001,0.0,U111,1
4163,48747830451,1010490,1007576,603355,20220919150003,30.54,31.32,32.1,30.6,31.56,...,0,0,0.0,31.519,0.00,3964162,20220919150004,0.0,E110,2
4164,48747848083,1010490,1007576,603355,20220919150006,30.54,31.32,32.1,30.6,31.56,...,0,0,0.0,31.519,31.56,3964266,20220919150006,0.0,E110,2
4165,48747534605,1010490,1007576,603355,20220919150102,30.54,31.32,32.1,30.6,31.56,...,0,0,0.0,31.519,31.56,3965282,20220919150102,0.0,E110,1
4166,48747551507,1010490,1007576,603355,20220919150503,30.54,31.32,32.1,30.6,31.56,...,0,0,0.0,31.519,31.56,3969947,20220919150503,0.0,E110,1