In [3]:
from cmschina_tianyan.session import CmsSession

dataset = CmsSession.init(appId="cb632213cf764a019b32f8cc9d2040b7", appSecret="b23700b9fbf0090709c7b72ac0fdcb390cd19cc663bcf1c7a07c12b8c32bf377")
data = dataset.get_data(
        '''
        select TRADE_DT from wind_admin.AShareEODDerivativeIndicator limit 10000
        ''')
print(data)

[2022-09-28T15:22:25.207868+0800] [42229] [INFO] [session.py] [63] PROD Env Init Completed!
[2022-09-28T15:22:25.208073+0800] [42229] [ERROR] [tianyan_provider.py] [134] Exception: TypeError("unsupported operand type(s) for -: 'NoneType' and 'int'")

TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'

In [ ]:
from WindPy import *

#Wind API 使用W账户密码登录
w.start() 

#return True and then can go to next operation.
w.isconnected()

import pandas as pd
wdata = w.wst("600000.SH", "last,volume,bid10,bid9,bid8,bid7,bid6,bid5,bid4,bid3,bid2,bid1,ask10,ask9,ask8,ask7,ask6,ask5,ask4,ask3,ask2,ask1", 
"2022-08-01 09:00:00", "2022-09-28 10:30:51", "",usedf=True)[1]
wdata

,LAST,VOLUME,BID10,BID9,BID8,BID7,BID6,BID5,BID4,BID3,...,ASK10,ASK9,ASK8,ASK7,ASK6,ASK5,ASK4,ASK3,ASK2,ASK1
2022-09-19 09:15:03,7.15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.15
2022-09-19 09:15:06,7.15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.15
2022-09-19 09:15:09,7.15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.15
2022-09-19 09:15:12,7.15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.15
2022-09-19 09:15:15,7.15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-09-28 10:30:37,7.07,7352894.0,NaN,NaN,NaN,NaN,NaN,7.02,7.03,7.04,...,NaN,NaN,NaN,NaN,NaN,7.11,7.1,7.09,7.08,7.07
2022-09-28 10:30:40,7.06,7355194.0,NaN,NaN,NaN,NaN,NaN,7.02,7.03,7.04,...,NaN,NaN,NaN,NaN,NaN,7.11,7.1,7.09,7.08,7.07
2022-09-28 10:30:43,7.06,7359094.0,NaN,NaN,NaN,NaN,NaN,7.02,7.03,7.04,...,NaN,NaN,NaN,NaN,NaN,7.11,7.1,7.09,7.08,7.07
2022-09-28 10:30:46,7.06,7371694.0,NaN,NaN,NaN,NaN,NaN,7.02,7.03,7.04,...,NaN,NaN,NaN,NaN,NaN,7.11,7.1,7.09,7.08,7.07
2022-09-28 10:30:49,7.06,7374194.0,NaN,NaN,NaN,NaN,NaN,7.02,7.03,7.04,...,NaN,NaN,NaN,NaN,NaN,7.11,7.1,7.09,7.08,7.07